---
 - name: install kubernetes packages
   become: yes
   yum:
     name: "{{item}}"
     allow_downgrade: yes 
   with_items:
     - kubelet-{{kubelet_version}}
     - kubeadm-{{kubeadm_version}}
     - kubectl-{{kubelet_version}}
     
 - name: enable kubelet
   systemd: 
     name: kubelet
     enabled: yes