---
 - name: installing etcd for centos distro to all masters
   yum:
     name: etcd
     state: latest
   when: 
       ansible_distribution == 'CentOS'

 - name: downloading etcd for redhat distro to all masters 
   get_url:
     url: https://www.rpmfind.net/linux/centos/7.9.2009/extras/x86_64/Packages/etcd-3.3.11-2.el7.centos.x86_64.rpm
     dest: /home/
     mode: 0777
   when: 
       ansible_distribution == 'RedHat'

 - name: installing etcd to redhat distro 
   shell: rpm ivh /home/etcd-3.3.11-2.el7.centos.x86_64.rpm
   when: 
       ansible_distribution == 'RedHat'


 - name: copying etcd.service to all masters
   template:
     src: etcd.service 
     dest: /etc/systemd/system/etcd.service

 - name: starting etcd 
   systemd:
     name: etcd
     state: started
     enabled: yes
     daemon_reload: yes

